### ISSUE TITLE
Migrate WCF Dockerfiles and image production into this repo

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/dotnet-framework-docker#302]
**Reasons**
1. Provides source code alignment with the [.NET Fx docker product family repo](https://hub.docker.com/_/microsoft-dotnet-framework/)
1. Customers are logging issues for the various .NET docker images within the wrong repos from time to time.  This consolidation eliminates the confusion on which repo to log issues with.
1. All of the .NET Fx Samples are already located within this repo.  Having all of the .NET Fx Dockerfiles used by the samples in the same location has value.
1. Having all of the .NET Fx Dockerfiles within a single repo eliminate overhead in sharing the same engineering infrastructure.

**Tasks**
- [x] Migrate Dockerfiles and readmes from https://github.com/Microsoft/wcf-docker to this repo.
- [x] Define manifest.wcf.json which describes the WCF Dockerfiles and the tags to use on the resulting images.
- [x] Define a WCF build definition.  I believe it will mimic the [Samples build](https://github.com/microsoft/dotnet-framework-docker/blob/master/.vsts-pipelines/builds/dotnet-framework-samples.yml) closely
- [x] Migrate the MCR WCF repo definition from iis to dotnet
- [x] Remove the WCF readme and tags metadata from the iis mcrdocs.  I believe the appropriate dotnet docs will get automatically created via the .NET build infrastructure.
- [x] Create the appropriate automated tests hooked up to the builds
- [x] Copy all open https://github.com/microsoft/wcf-docker issues to https://github.com/microsoft/dotnet-framework-docker
- [x] Archive the https://github.com/microsoft/wcf-docker repo
~~- [ ] Hookup WCF builds to docker-tools base image change detection system~~

**Comment by MichaelSimons** [comment]
This work has been completed.  Closing.
