### ISSUE TITLE
Patch Tuesday Release - 2B

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#513]
# Patch Tuesday Release - 2B

## Tasks

1. - [x] Merge any pending PRs or commits from `dev` branch:
      - [x] &lt;placeholder link&gt;
1. - [x] Look up the latest [NuGet CLI versions](https://www.nuget.org/downloads) and update the [nuget-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/nuget-info.json) file with the latest patch of each major/minor version listed in the file.
1. - [x] Wait for latest cumulative updates (LCUs) to be released (typically at 10 AM PST on Patch Tuesday).
1. - [x] Gather list of KB numbers for the .NET Framework updates from the .NET Release team.
1. - [x] Look up the download URL for each of the KB numbers in [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/) and input them into the [lcu-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/lcu-info.json) file.
1. - [x] Run the `update-dependencies` tool to update all the necessary files:
      - [x] `dotnet run --project .\eng\update-dependencies --datestamp-all <YYYYMMDD>`
1. - [x] Inspect generated changes for correctness
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR
1. - [x] Wait for changes to be mirrored to internal [dotnet-framework-docker repo](https://dev.azure.com/dnceng/internal/_git/Microsoft-dotnet-framework-docker) (internal MSFT link)
1. - [x] Wait for the following Windows images to have been updated as part of the Windows Patch Tuesday release process (this begins at 10 AM PST on Patch Tuesday):
      - [x] `mcr.microsoft.com/windows/servercore:1903`
      - [x] `mcr.microsoft.com/windows/servercore:1909`
      - [x] `mcr.microsoft.com/windows/servercore:ltsc2016`
      - [x] `mcr.microsoft.com/windows/servercore:ltsc2019`
1. - [x] Queue build of [dotnet-framework-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=372) (internal MSFT link)
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in Docker Hub for [microsoft-dotnet-framework](https://hub.docker.com/_/microsoft-dotnet-framework)
1. - [x] Confirm build for [dotnet-docker-framework-samples](https://dev.azure.com/dnceng/internal/_build?definitionId=374) (internal MSFT link) was queued. This will be queued automatically by [dotnet-docker-tools-check-base-image-updates](https://dev.azure.com/dnceng/internal/_build?definitionId=536) when it detects that the product images have been updated (detection runs on a schedule). Alternatively, you can manually queue the samples build.
1. - [x] Confirm sample images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-framework-samples](https://hub.docker.com/_/microsoft-dotnet-framework-samples/)
1. - [x] Reply to .NET Release team with a status update email

**Comment by mthalman** [comment]
Image publishing is currently blocked due to connectivity issues on the Docker host machines.

**Comment by kfolkes** [comment]
@mthalman Can we get an update when this will be released ?

**Comment by mthalman** [comment]
@kfolkes - Not yet known.  There's currently a major blocker that we're dealing with.

**Comment by mthalman** [comment]
See https://github.com/dotnet/dotnet-docker/issues/1674#issuecomment-585925527 for latest info on the blocked status.

**Comment by daviddarling** [comment]
@mthalman Do you have a sense for if/when the images will be released?  Thanks!

**Comment by mthalman** [comment]
The plan is to have them released later today.

**Comment by mquekel** [comment]
Looking at the Pull Request, I am wondering should the image for 1903 and 1909 also be updated? https://github.com/microsoft/dotnet-framework-docker/tree/master/4.8/runtime

They are using microsoft-windows-servercore as base image with tag 1903. But this tag is still pointing to the older version, according to this article https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im

**Comment by mthalman** [comment]
Right, the plan is for Windows to have their images updated to fix the issue and then the .NET Framework images will be updated after that.

**Comment by mthalman** [comment]
We're now resuming the process of publishing the images.

**Comment by mthalman** [comment]
The February 11, 2020 security update for Windows introduced compatibility issues between the version of Windows on the Docker host versus the Docker container.  You can read about that here: https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

**Comment by mthalman** [comment]
The `runtime`, `sdk`, `wcf`, and `aspnet` repos have all been updated.  The `samples` repo is currently in progress.

**Comment by mthalman** [comment]
Publishing for all images is complete.

**Comment by jaredthirsk** [comment]
Is this likely to ever happen again?  This disrupted some of my containers.  I guess this is a lesson to keep backups of older Windows Servers in case a Windows Update breaks docker images, for 12 days in this case.

**Comment by MichaelSimons** [comment]
@jaredthirsk, FWIW I apologize for the inconvenience.  This was outside of the control of the .NET team as it was an issue with the Windows.  I can tell you that we have been in communications with the Windows container team to help ensure the appropriate testing is in place to catch issues like this.  We are also investigating ways that we can test the .NET images against pre-release versions of the Windows images.
