### ISSUE TITLE
Patch Tuesday Release - 3B

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#533]
# Patch Tuesday Release

## Tasks

1. - [x] Merge any pending PRs or commits from `dev` branch:
      - [x] &lt;placeholder link&gt;
1. - [x] Look up the latest [NuGet CLI versions](https://www.nuget.org/downloads) and update the [nuget-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/nuget-info.json) file with the latest patch of each major/minor version listed in the file.
1. - [x] Wait for latest cumulative updates (LCUs) to be released (typically at 10 AM PST on Patch Tuesday).
1. - [x] Gather list of KB numbers for the .NET Framework updates from the .NET Release team.
1. - [x] Look up the download URL for each of the KB numbers in [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/) and input them into the [lcu-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/lcu-info.json) file. If this is the first Patch Tuesday after the release of a new Windows version, you'll need to do the following extra steps for that version:
      - [ ] Add a new entry to the [lcu-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/lcu-info.json) file to associate a URL for the new Windows version and `3.5` runtime version.
      - [ ] Update the `3.5/runtime` Dockerfile for the new Windows version so that the patch is applied (this can be copied from another `3.5/runtime` Dockerfile in a section labeled `Apply latest patch`)
1. - [x] Run the `update-dependencies` tool to update all the necessary files:
      - [x] `dotnet run --project .\eng\update-dependencies --datestamp-all <YYYYMMDD>`
1. - [x] Inspect generated changes for correctness
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR
1. - [x] Wait for changes to be mirrored to internal [dotnet-framework-docker repo](https://dev.azure.com/dnceng/internal/_git/Microsoft-dotnet-framework-docker) (internal MSFT link)
1. - [x] Run the [`Get-BaseImageStatus.ps1`](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/common/Get-BaseImageStatus.ps1) script and wait until the Windows images have been updated as part of the Windows Patch Tuesday release process. This script will display when the dependent Windows images were last updated. Wait until all the images show that they have been recently updated. "Recently updated" amounts to be having been updated within the past week or so; images from a month ago should be considered to be the old version.

          ./eng/common/Get-BaseImageStatus.ps1 -Continuous
1. - [x] Queue build of [dotnet-framework-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=372) (internal MSFT link) with the following `imageBuilder.pathArgs` variable value:

          --path '*190*' --path '*ltsc2019*'
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in Docker Hub for [microsoft-dotnet-framework](https://hub.docker.com/_/microsoft-dotnet-framework)
1. - [x] When ltsc2016 base Windows image has been updated, queue build of [dotnet-framework-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=372) (internal MSFT link) with the following `imageBuilder.pathArgs` variable value:

          --path '*ltsc2016*'
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in Docker Hub for [microsoft-dotnet-framework](https://hub.docker.com/_/microsoft-dotnet-framework)
1. - [x] Confirm build for [dotnet-docker-framework-samples](https://dev.azure.com/dnceng/internal/_build?definitionId=374) (internal MSFT link) was queued. This will be queued automatically by [dotnet-docker-tools-check-base-image-updates](https://dev.azure.com/dnceng/internal/_build?definitionId=536) when it detects that the product images have been updated (detection runs on a schedule). Alternatively, you can manually queue the samples build.
1. - [x] Confirm sample images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-framework-samples](https://hub.docker.com/_/microsoft-dotnet-framework-samples/)
1. - [x] Reply to .NET Release team with a status update email

**Comment by mthalman** [comment]
Due to a delay in the availability of the updated `mcr.microsoft.com/windows/servercore:ltsc2016` image, the release will publish 2016-based images either later today or tomorrow, depending on the time when the base image gets updated.  For now, all other images that are not based on 2016 are in the process of being published.

**Comment by mthalman** [comment]
ETA for 2016 images is tomorrow.

**Comment by mthalman** [comment]
All .NET Framework images that aren't based on `ltsc2016` have completed publishing.

**Comment by mthalman** [comment]
New ETA for updates is tomorrow.

**Comment by mthalman** [comment]
All images have been published.  In addition to LTSC 2016, 1903 and 1909 were also updated today because of changes to the base Windows images.
