### ISSUE TITLE
Patch Tuesday Release - 4B

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#558]
# Patch Tuesday Release

## Tasks

1. - [x] Merge any pending PRs or commits from `dev` branch:
      - [x] #531
1. - [x] Look up the latest [NuGet CLI versions](https://www.nuget.org/downloads) and update the [nuget-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/nuget-info.json) file with the latest patch of each major/minor version listed in the file.
1. - [x] Wait for latest cumulative updates (LCUs) to be released (typically at 10 AM PST on Patch Tuesday).
1. - [x] Gather list of KB numbers for the .NET Framework updates from the .NET Release team.
1. - [x] Look up the download URL for each of the KB numbers in [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/) and input them into the [lcu-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/lcu-info.json) file. If this is the first Patch Tuesday after the release of a new Windows version, you'll need to do the following extra steps for that version:
      - [ ] Add a new entry to the [lcu-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/lcu-info.json) file to associate a URL for the new Windows version and `3.5` runtime version.
      - [ ] Update the `3.5/runtime` Dockerfile for the new Windows version so that the patch is applied (this can be copied from another `3.5/runtime` Dockerfile in a section labeled `Apply latest patch`)
1. - [x] Run the `update-dependencies` tool to update all the necessary files:
      - [ ] `dotnet run --project .\eng\update-dependencies --datestamp-all <YYYYMMDD>`
1. - [x] Inspect generated changes for correctness
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR
1. - [x] Wait for changes to be mirrored to internal [dotnet-framework-docker repo](https://dev.azure.com/dnceng/internal/_git/Microsoft-dotnet-framework-docker) (internal MSFT link)
1. - [x] Run the [`Get-BaseImageStatus.ps1`](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/common/Get-BaseImageStatus.ps1) script and wait until the Windows images have been updated as part of the Windows Patch Tuesday release process. This script will display when the dependent Windows images were last updated. Wait until all the images show that they have been recently updated. "Recently updated" amounts to be having been updated within the past week or so; images from a month ago should be considered to be the old version.

          ./eng/common/Get-BaseImageStatus.ps1 -Continuous
1. - [x] Queue build of [dotnet-framework-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=372) (internal MSFT link)
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in Docker Hub for [microsoft-dotnet-framework](https://hub.docker.com/_/microsoft-dotnet-framework)
1. - [x] Confirm build for [dotnet-docker-framework-samples](https://dev.azure.com/dnceng/internal/_build?definitionId=374) (internal MSFT link) was queued. This will be queued automatically by [dotnet-docker-tools-check-base-image-updates](https://dev.azure.com/dnceng/internal/_build?definitionId=536) when it detects that the product images have been updated (detection runs on a schedule). Alternatively, you can manually queue the samples build.
1. - [x] Confirm sample images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-framework-samples](https://hub.docker.com/_/microsoft-dotnet-framework-samples/)
1. - [x] Reply to .NET Release team with a status update email

**Comment by nrodrigues1** [comment]
@mthalman 

Hello, 

I would like to know why "4.8-20200211-windowsservercore-ltsc2016" has not received the KB update while 4.7.2 and down where updated twice since February? 


Also, why kb4550929 was updated directly in the dockerfile if "mcr.microsoft.com/windows/servercore:ltsc2016" is version 10.0.14393.3630 and matches https://support.microsoft.com/en-ca/help/4550929/windows-10-update-kb4550929?

Thank you!

**Comment by mthalman** [comment]
@nrodrigues1 - Which KB are you expecting for 4.8 on 2016?  The one that is currently installed, KB4534126, is the latest 4.8 security update for that OS.  The other Dockerfiles explicitly install KB4550929 because they're also installing a version of .NET Fx.  After installing .NET Fx, it needs to be patched with the latest Windows LCU.

**Comment by nrodrigues1** [comment]
@mthalman 

Thank you for the great answer sir!

**Comment by aidanfolkes** [comment]
@nrodrigues1 Shouldn't the base images have been updated per the [Image Update Policy](https://hub.docker.com/_/microsoft-dotnet-framework-runtime/).
I ask because we're having issues after KB4550929 was applied to the host OS (on a test server) and according to [Windows container version compatibility](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2016%2Cwindows-10-1909): 
> Windows Server containers currently don't support scenarios where Windows Server 2016-based containers run in a system where the revision numbers of the container host and the container image are different.

**Comment by mthalman** [comment]
@aidanfolkes - As per the policy, the images do get rebuilt when a new base Server Core image is made available.  And as part of that, the latest security KB is applied to the images.  What image tag are you using and how does its version compare to your host?

**Comment by aidanfolkes** [comment]
@mthalman 
Image tag is 4.8-windowsservercore-ltsc2016
Host version is 10.0.14393.3630
Container version is 10.0.14393.3568
I'm beginning to suspect that we need to add --pull to the docker build command though.

**Comment by mthalman** [comment]
> Host version is 10.0.14393.3630
> Container version is 10.0.14393.3568
> I'm beginning to suspect that we need to add --pull to the docker build command though.

Yes, using `--pull` would definitely be recommended to ensure you're using the latest image.  The latest version of the image is using version 10.0.14393.3630.

**Comment by aidanfolkes** [comment]
That appears to be the problem. Thanks.
